//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Ciudades
    {
        public C_Ciudades()
        {
            this.C_Clientes = new HashSet<C_Clientes>();
        }
    
        public int idCiudad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
    
        public virtual C_Municipios C_Municipios { get; set; }
        public virtual ICollection<C_Clientes> C_Clientes { get; set; }
    }
}
