//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Ciudades
    {
        public C_Ciudades()
        {
            this.C_Clientes = new HashSet<C_Clientes>();
        }
    
        public int IdCiudad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
    
        public virtual C_Municipios C_Municipios { get; set; }
        public virtual ICollection<C_Clientes> C_Clientes { get; set; }
    }
}
