//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Clientes
    {
        public C_Clientes()
        {
            this.C_Vehiculos = new HashSet<C_Vehiculos>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdCliente { get; set; }
        public string RFC { get; set; }
        public string NumeroCliente { get; set; }
        public string Nombre { get; set; }
        public int IdTipoPersona { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public int IdMunicipio { get; set; }
        public Nullable<double> Movil { get; set; }
        public Nullable<double> Casa { get; set; }
        public Nullable<double> Trabajo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual C_TiposPersona C_TiposPersona { get; set; }
        public virtual ICollection<C_Vehiculos> C_Vehiculos { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
        public virtual C_Municipios C_Municipios { get; set; }
    }
}
