//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Clientes
    {
        public C_Clientes()
        {
            this.C_Vehiculos = new HashSet<C_Vehiculos>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdCliente { get; set; }
        public string RFC { get; set; }
        public string NumeroCliente { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IdTipoPersona { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> IdCiudad { get; set; }
        public Nullable<int> CodigoPostal { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<decimal> Movil { get; set; }
        public Nullable<decimal> Casa { get; set; }
        public Nullable<decimal> Trabajo { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<int> IdEstado { get; set; }
    
        public virtual C_Ciudades C_Ciudades { get; set; }
        public virtual C_Municipios C_Municipios { get; set; }
        public virtual C_TiposPersona C_TiposPersona { get; set; }
        public virtual ICollection<C_Vehiculos> C_Vehiculos { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
