//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Estados
    {
        public C_Estados()
        {
            this.C_Municipios = new HashSet<C_Municipios>();
        }
    
        public int IdEstado { get; set; }
        public string Descripcion { get; set; }
        public int Estatus { get; set; }
    
        public virtual ICollection<C_Municipios> C_Municipios { get; set; }
    }
}
