//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Estados
    {
        public C_Estados()
        {
            this.C_Municipios = new HashSet<C_Municipios>();
        }
    
        public int IdEstado { get; set; }
        public string Descripcion { get; set; }
        public int Estatus { get; set; }
    
        public virtual ICollection<C_Municipios> C_Municipios { get; set; }
    }
}
