//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Municipios
    {
        public int IdMunicipio { get; set; }
        public int IdEstado { get; set; }
        public string Descripcion { get; set; }
        public int Estatus { get; set; }
    
        public virtual C_Estados C_Estados { get; set; }
    }
}
