//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Servicios
    {
        public C_Servicios()
        {
            this.Inventario = new HashSet<Inventario>();
            this.Precios = new HashSet<Precios>();
            this.VentasDetalle = new HashSet<VentasDetalle>();
        }
    
        public int IdServicio { get; set; }
        public string Descripcion { get; set; }
        public int IdUnidadMedida { get; set; }
        public Nullable<bool> SeAlmacena { get; set; }
        public Nullable<bool> SeCompra { get; set; }
        public Nullable<bool> SeVende { get; set; }
        public int IdMarca { get; set; }
        public Nullable<int> IdTipoServicio { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public int Estatus { get; set; }
        public string Codigo { get; set; }
    
        public virtual C_Marcas C_Marcas { get; set; }
        public virtual C_TiposServicios C_TiposServicios { get; set; }
        public virtual C_UnidadesMedida C_UnidadesMedida { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual ICollection<Precios> Precios { get; set; }
        public virtual ICollection<VentasDetalle> VentasDetalle { get; set; }
    }
}
