//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_UnidadesMedida
    {
        public C_UnidadesMedida()
        {
            this.C_Servicios = new HashSet<C_Servicios>();
        }
    
        public int IdUnidadMedida { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual ICollection<C_Servicios> C_Servicios { get; set; }
    }
}
