//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Vehiculos
    {
        public C_Vehiculos()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdVehiculo { get; set; }
        public string Placas { get; set; }
        public string Marca { get; set; }
        public string Linea { get; set; }
        public Nullable<int> Modelo { get; set; }
        public string Color { get; set; }
        public string NoEconomico { get; set; }
        public int IdCliente { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual C_Clientes C_Clientes { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
