//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Vehiculos
    {
        public C_Vehiculos()
        {
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdVehiculo { get; set; }
        public string Placas { get; set; }
        public string Marca { get; set; }
        public int IdTipo { get; set; }
        public string Linea { get; set; }
        public Nullable<int> Modelo { get; set; }
        public string Color { get; set; }
        public string NoEconomico { get; set; }
        public int IdCliente { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual ICollection<Ventas> Ventas { get; set; }
        public virtual C_Clientes C_Clientes { get; set; }
    }
}
