//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int IdFactura { get; set; }
        public int IdVenta { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaCertificacion { get; set; }
        public long CertificadoEmisor { get; set; }
        public long CertificadoSAT { get; set; }
        public string CadenaOriginalCertificacionSAT { get; set; }
        public string SelloDigitalEmisor { get; set; }
        public string SelloDigitalSAT { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
