//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int IdFactura { get; set; }
        public int IdVenta { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public System.DateTime FechaCertificacion { get; set; }
        public long CertificadoEmisor { get; set; }
        public long CertificadoSAT { get; set; }
        public string CadenaOriginalCertificacionSAT { get; set; }
        public string SelloDigitalEmisor { get; set; }
        public string SelloDigitalSAT { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
    
        public virtual Ventas Ventas { get; set; }
    }
}
