//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int IdInventario { get; set; }
        public int IdServicio { get; set; }
        public double PrecioCompra { get; set; }
        public double PrecioVenta { get; set; }
        public double Cantidad { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string Serie { get; set; }
    
        public virtual C_Servicios C_Servicios { get; set; }
    }
}
