//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public Pagos()
        {
            this.PagosDetalle = new HashSet<PagosDetalle>();
        }
    
        public int IdPago { get; set; }
        public int IdVenta { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual Ventas Ventas { get; set; }
        public virtual ICollection<PagosDetalle> PagosDetalle { get; set; }
    }
}
