//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Pagos = new HashSet<Pagos>();
            this.VentasDetalle = new HashSet<VentasDetalle>();
        }
    
        public int IdVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Folio { get; set; }
        public double Subtotal { get; set; }
        public double IVA { get; set; }
        public double Total { get; set; }
        public string TotalLetras { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> Kilometraje { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public bool EsFactura { get; set; }
    
        public virtual C_Clientes C_Clientes { get; set; }
        public virtual C_Vehiculos C_Vehiculos { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<VentasDetalle> VentasDetalle { get; set; }
    }
}
