//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public Ventas()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Pagos = new HashSet<Pagos>();
            this.VentasDetalle = new HashSet<VentasDetalle>();
            this.VentasVehiculos = new HashSet<VentasVehiculos>();
        }
    
        public int IdVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Folio { get; set; }
        public double Subtotal { get; set; }
        public double IVA { get; set; }
        public double Total { get; set; }
        public string TotalLetras { get; set; }
        public int IdCliente { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> Kilometraje { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> IdUsuarioCreacion { get; set; }
        public Nullable<int> IdUsuarioModificacion { get; set; }
        public Nullable<int> Estatus { get; set; }
        public bool EsFactura { get; set; }
    
        public virtual C_Clientes C_Clientes { get; set; }
        public virtual C_Vehiculos C_Vehiculos { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Pagos> Pagos { get; set; }
        public virtual ICollection<VentasDetalle> VentasDetalle { get; set; }
        public virtual ICollection<VentasVehiculos> VentasVehiculos { get; set; }
    }
}
