//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerWPF.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasVehiculos
    {
        public int IdVenta { get; set; }
        public int IdVehiculo { get; set; }
        public double Kilometraje { get; set; }
        public string Observaciones { get; set; }
    
        public virtual C_Vehiculos C_Vehiculos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
